### ISSUE TITLE
Camel 4 support

### ISSUE THREAD

**Issue by pbloigu** [ncasaux/camel-plantuml#13]
Hi!

I think this library should support Camel 4. I already started preliminary work towards this goal here: https://github.com/pbloigu/camel-plantuml/commit/e45c5408b8a6f8b7e58c0797b116356632cf5365

**Comment by ncasaux** [comment]
Thanks for your interest in this project! 

I just published a 1.6.0 version which should be soon available in maven central. So don't hesitate to let me know it works as expected! 😃
