### ISSUE TITLE
your serveur plantuml.com is very very slow. or is down ? i try see apache camel route with plantUML plugin

### ISSUE THREAD

**Issue by marteloudini** [ncasaux/camel-plantuml#15]
Hello,

why im obliged to goto your site for view my graph ?
and i see nothing. 

[plantUML_diagram](http://www.plantuml.com/plantuml/img/jLlRSXl74NtdLw2Kf9Gya9hxHIMf8j5Iv2hBTgnKd3VMN7eeb40iim1rYSl_dhCa9G3S1GOBodm20VBqJ4_twTFJYxylbg5TNbtCZeuMxwVpoz26Yydpjcq-dZQpfftywSKifFVh7xQKbc5-FgF9RqUJoI_DrJoVDksSsebWHxyF_kMJ9srpjQHdpwx_vKNJPcfluSsfU_dYLVSkp9otDsZNdtpt_ALxTRg9-DyhkW8QpVDbCvqlhm67_W2RMaxJaBqNJYlDXkozSgSlJuVjvS_pS36CvyGBQSpW-lLBzvtgy4hJBE6UVn2S59QK9n-dotUJ52veTdmv2_FE_PDcFlbBngT_VP3pyPitnv_nCtdz-l75nOE_7Hqzd3nz-dJojhcWoTM2ojLiig3bSZe_NqmAZ2q_Ki2YpoTv6iwxXS_2PtYy-wUZXpCgoycocRJJytTB_4LtBDDcVlJmtJJJP86bKRFyV4b73rSRdpUP5dGvWQlMtct3_7t_tOzjkFnrch4bWG-ELl5nVUXdmR2OOWui6MzvKbchQ5nEAeWKaukJLNI4nUJ14I7usXTNqncSVFIWZnU3bDgPd1LpoWLhcSShpOekjWJfxkB1KQyf06pngcqkNeV_qIo5nVBe13z7JwRFflEJsEJFawUJwJmr5_3YBuHpNooVF9e-6re0JoGj30OdfEIU5N8yUACo2qM4PFiB26rwzmeHDFjysbnSDejfv_yNdzykflFdy_mTJdrWDO0uRwvNixXivWlQjXnMZ7DI2a5EKd4oiiojjYeABhNg-tT9wTryciBi-pcEVXvcBpk7tsC1CkMYYXMX4ENCaYxEwgYbLq84gNr_0OlbgrdpyVjCy-MqJ8UFkUX0AGklI34HY_E87kMAY4bmdYdrmkRJvTavZhf1VhnhPldmyqMKicWLio9X4S5nupXoNAlYiHQMxre-lmcmdyeks_iwirZck4jC2kUpLoLHTjgQP4gIN6PnrtYyGX3HOl5pstn0EhVtFSp2L31PKHI2sGYNm_F55EiYPo7xVhRUkhtgW3sTdqWf9PmItcIUd395C6-uoGQCOJKVSFwFLnUHsZNhRwXxOt4VBv2E54Dq9PjOU4gPSswu5bIOrRwtYfqfVezrXEAnxTmnZN5Q1D9SCnwvyDP7BuUyyTKBBpyWlUxZXCnL2BnuGO6JZIRYO2AeDth1f66zlBwRWLiNi6SeY60A3pA6P2plyizhIy7cw1nZGVNoiBC_NNopI6Gy11bOL549L1OcCo4cdAC8wpQKRPduhMWraqoyX6Zm8gD-SYL03P8PpOCBgUV-zAcy_8J8e_oMsWyqP7hV0cU59YDbqJO6ex40ePEFN2kRTP6zdTyU_8Wyt7CXrX6gMYw1Z5CSwG_ZHGWJWj8em3qoskVqzwvg23VXT78fAgCi5HLY1W5c-8Qns4kzwryust-przfoyaNAdja4ZYr5Pm5bf8FGmQhiM236jH6cS_fAzguft6lZDwBkyQD7MufxtnmNO7Te1PujkMA3XOg9EYYof0q9iP-vRTggRqybQprC9GyZMViGoS0uXv2JaOBRQU_JOhOyNeHFpHmsySkZFitSElS4dmvO5qL37y6x33kLYO84kqlYmQ3CwfJttUqUGgvlt4WB6bL6U6y2Cqf5A3Me9OubHSVqkAql8S8NqFmNPzT2-T5_tlvm_Aylxnqlcd3p_ja7liKNsRb0XSTKZ8m-oaAA2nBofhvQ-eEM8xSiHuV4S3WwQ8jmI5PdpZWX6H27aSJkmFXwDCFasxS6eKn92OAoafeeuNUq3Deh9ndKwkuiwst-nUdRjuzsnyE_nHUYsRB_c1IAgX522QMxOkjDOYXmqbYFoZVoEFPSqQvSOT8bwo4u2RcAbQ1zyvs-zqPOBYqVTo2RkdGWESZ427kAPIh9m1levuha3anlazoT75-jxQe-0pO5gHX0vs2w57nce31fecG8DyxqxXsESddDrvGjA8aWD3A4PH4sSvEKP99y58cP_NO_B7m6Ianq4bhIffJGgQNeEUa2PGcnA-7u4TOs6gq1icS2ciKnfI3W6RI40G4Nx8j9QDThvJYIx3VtLaaf15F8MNPIoKF55Iaa-dFYJe1HB5VxxNCVZoReObiCP557f2RgWegM2X87QeN4o4ZgMQpiqtW50aEBdPrnqGaGkq4v1OqvJTRl9ZF8nIvDASmVRyh6lftWWzCEAZ0ML2_qXYXZEkO4ESuZHEcth1WH3M-jWZdm0jPa4cfNHfSEIjSQcZoNKdXsky_tUiVTnay-XjcicK_fP77vyUHYcbeueVqmJNG2lNRHp4-kEUiDI2oSqzg5rDrWHozccU1QbgYSiumZbQqAHJkZoOS_g9wgRVHj39PZDTnZP13evj6qUQzYHEOBBh-1r1aIMD8gmQFFEXeRIx2SqCFBv0DZAl6q9xNSkVhh2IcH38zIMLHAaxGAe6lf27IPIWcxFRqMxnrZdywca8r3yaWIUZxqdMJGPMY3ra-Hi0pU0tsctJiPugvjXQcIt2Keb5oKAjvTTnOlYulPGowQOD2Fx-dHWNvye0fPjBa5x84qyZ4I6W9DJb-dTqHTlZzTxzJcw3OAMW-McVBEPOq3I1RzhiCv2BkRNKPayzVkPElHSoCHNL0T147AIwQiEy43FPgpBMpFkb7hXljsqG1Hui8x4pgXbQ5DWqyI-PkOud5tNLwFwv_UFh_Pt9iclH-K_a999KCX3qR8nahAf3bv3ZQdFB9SxKrLUil9S-kPLmQzY6AI9-ECZzYqXY3i8luRz8IxCmpaeOJEAf16q6Lq-yP1TZjHLFGwVbiPk5kna6TGAGRCngA8Jha8ZkCKL8herNOVp6qE_D2S__CgjE-l5gVTP0adaOQwKPaHp9uGtZ5opb4oCwHH4YZnXAZRtGeFakYMO9CUeiz81aKBFQG3KM5USY_G33DXziocuM51Bu4i9Br6WozSmUkGG2HKH8POGI5YuuHjLVK9wK0AtQLW5y51InG9i4PYqJ1ASMGJUNux5lmrjFFf_BnhqNvibZ-tjC2EjyKBEdYlPT31aTJ85a7P5tBTtLGiQNUy33B645iefbK99K786-EyiSL7AutMANPJaMzO2NVL1qtH1QkCxcxXI0LhRI17CQDL3j0S-nV2UeDK6DTMAkfQKSyPIpBRt4rWa9wCzcnzjzo33pbOmgk4-Ca2YbfOM5NQ2ud6B454thjxsELMcqMoXB9FtUw4PEWWE2icQ4WfD37xxRMziN5yYMDivZS7VDnIePRcYRPSY87hfPGehcYvqLA8Y8RDS2XKQ3XluvuITNhtgcV_AwNZusVxNl8_dfIskLW3hrwFhC2hixmUUBMZMu5NnmCzyAf6Nu5NP_Ozy2e5hxcbDcBiWLSlBjR0QsFZFdWjwTTyNfk8zS2had85NfswzC2hjqShyEeihGTUfTqLU7LWtWElDZTheLWRWVQJg7Qbk0AlJfjxuDMxfHLuTNhL3yKQ9w_0g-EfFd7LBWRMagWs_kvpIst0iXRdjSTd-abKcrMjmAiF1_LzNfkxhHMBsfCsVLQiQU2r0wqzHVC5V4_wxv3tt-JZoR8v3BhQkgn3LzbvSzMrTDY0hbMLmw6hv7auT9Nq3uUk5gl3eQlaim5TJT_3eQkTs4Q4r5Xj0xew93eSkjg2tsFLjIlImw6hroKRSLqZ-GtewWpqSEXHlXu7FShNuw2hO-frwAhyse2kNlOU3btjw-u1NRiYFHowUfToE7Hr3heENHMwcz2rvsaEXnxbwt7Getmz3hfwcRmENTNz6z3LYx33eKVvUXpqA5-FT4XjHhOENMs3xlYwSYTsEFGeNu-37kNhST3LHmpMeQljpwPwgatUDeHPhJ_PWAvUmQr3Lo_XDcjZRVf_EFIeNcOSTFNoRGEwrcZUmo6ZeCSvP1JqA8TKRr8FTyWuw77TxYZeKGwfNj1kG5SVu3aSklfmw-7GrGTL3uUkFhDpdrLNPkmtq3SZaTil5fvTjas-IjIUhGWKRaKjKAX_0GfT6c-SjKO5ZcFaxEv8S_KDnSqXoPz_UtVzVFR9vUrpc6VDPJTjd3Rptw-VUj-_wRx7MXztNmMTNdPpnX-cYsLzzo5nLGndWJWwRqaI7QQGQCWPgeWDTsV7stRVJUA-Uk3hndyC5xIs-Rskk-wnrDxc_ux_xRvm-ty0)

is possible to run server on premise ?
thanks you

**Comment by ncasaux** [comment]
Hello,

PlantUML is a external resource, which is not my site, neither my tool, and I am not related to it 😉 
I don't know how you generated the string in your example, so I'm not sure how to help... 😞 
How did you generate it ?

**Comment by marteloudini** [comment]
https://camel.apache.org/blog/2021/05/plantuml-diagram
i want just see the graph of my routes, localy or remote :-)

**Comment by ncasaux** [comment]
Once started, what do you get when you browse to `http://localhost:8090` ?
