### ISSUE TITLE
Camel 3.16+ throws NoSuchMethodError

### ISSUE THREAD

**Issue by rob42** [ncasaux/camel-plantuml#9]
Hi,
Nice project!
See https://camel.apache.org/manual/camel-3x-upgrade-guide-3_16.html
Search for 'RestOperationParamDefinition'. The class has been renamed to 'ParamDefinition' which causes:

```
Caused by: java.lang.NoSuchMethodError: 'org.apache.camel.model.rest.RestOperationParamDefinition org.apache.camel.model.rest.RestDefinition.param()'
	at io.github.ncasaux.camelplantuml.routebuilder.CamelPlantUmlRouteBuilder.configure(CamelPlantUmlRouteBuilder.java:51)
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:672)
```
Using Camel 3.18, and your version 1.3.0 on jdk11. Sorry I cant create a pull request, all sort of security problems from my work env.

Rob

**Comment by rob42** [comment]
I managed to pulled the repo via zip(!) and fixed the problem, but I cant connect back. The issue can be solved by updating the pom to camel 3.18.0, and  editing CamelPlantUmlRouteBuilder.java. It breaks the tests but works for me. 
```
public void configure() throws IOException {

        if (jmxHost != null) {
            LOGGER.info("Testing MBean server connection from provided jmxHost \"".concat(jmxHost).concat("\""));
            JMXConnector connector = JmxUtils.getConnector(jmxHost);
            connector.getMBeanServerConnection();
            connector.close();
            LOGGER.info("MBean server connection successfully tested");
        }

        restConfiguration().component("netty-http").host(host).port(port);

        rest("camel-plantuml")
                .get("diagram.puml")
                    .param().name("connectRoutes").type(RestParamType.query).defaultValue("false").endParam()
                    .to("direct:process-uml");
        from("direct:process-uml").routeId("camel-plantuml-http-trigger")
                    .process(new GetRoutesInfoProcessor());
                
    }```

**Comment by rob42** [comment]
oh, and had the unintended effect of showing the CamelPlantUml route in the output :-( 
But I was able to edit it out of the dot file

**Comment by ncasaux** [comment]
hello @rob42 ,
Thanks for reporting this, I'll have a look this week.

**Comment by ncasaux** [comment]
I had a look, and I'm facing this problem:
when I declare the REST route as you suggest (which is the right way starting from Camel 3.16), I can't set the routeId of the route. Hence, I can't filter it and it appears in the diagram, which is not really desired. The routeId is always `route1`, I can't really filter this...

There is an issue on this topic here: https://issues.apache.org/jira/browse/CAMEL-18057

I'm not sure how I could properly fix this for now... 🤔

**Comment by rob42** [comment]
In my view its more useful to have the diagram with the CamelPlantUml route in the output, than no diagram at all.
Its not hard to manually delete the CamelPlantUml route in the output dot file.
If it doesnt work at all then I have no easy way to show the deployment/queues/etc info.

I'll look into some way to pick and avoid it

**Comment by rob42** [comment]
After some thought a solution seems possible using netty or jetty instead of rest. I dont think they are affected by the 3.16 change

**Comment by ncasaux** [comment]
Version 1.4.0 should be available in a few hours on maven central.
Please let me know if it's ok!
